import sys
import streamlit as st

# --- NEW IMPORTS ---
from src.utils.logger import logger
from src.utils.exception import CustomException

def render_candidate_card(candidate, questions):
    """
    Renders a clean, expandable UI card for a ranked candidate and their interview questions.
    """
    try:
        # We use a debug log here so we don't spam the log file if there are 50+ candidates
        logger.debug(f"Rendering UI card for candidate: {candidate.profile.name}")
        
        # Color code the score
        if candidate.match_score >= 80:
            score_color = "green"
        elif candidate.match_score >= 60:
            score_color = "orange"
        else:
            score_color = "red"

        with st.expander(f"👤 {candidate.profile.name} - Match: :{score_color}[{candidate.match_score:.2f}%]"):
            st.write(f"**Experience:** {candidate.profile.experience_years} years | **Education:** {candidate.profile.education}")
            st.write(f"**Skills:** {', '.join(candidate.profile.skills)}")
            st.markdown("---")
            
            st.subheader("Professional Summary")
            st.write(candidate.profile.summary)
            
            # Display the custom interview questions generated by Agent 4
            if questions:
                st.markdown("---")
                st.subheader("🎯 Personalized Interview Questions")
                
                st.markdown("**Technical:**")
                for q in questions.get("technical", []):
                    st.markdown(f"- {q}")
                    
                st.markdown("**Behavioral:**")
                for q in questions.get("behavioral", []):
                    st.markdown(f"- {q}")
                    
                st.markdown("**Role-Specific:**")
                for q in questions.get("role_specific", []):
                    st.markdown(f"- {q}")
                    
    except Exception as e:
        # Fallback to 'Unknown' just in case the candidate object itself is corrupted
        candidate_name = getattr(candidate.profile, 'name', 'Unknown')
        logger.error(f"UI Rendering failed for candidate card: {candidate_name}")
        
        # Display a localized error message in the UI so the whole app doesn't crash
        st.error(f"⚠️ Could not load profile card for {candidate_name}.")
        raise CustomException(e, sys)


